#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -v" \
	mv="mv -v" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	vim="nvim" \

# Colorize commands when possible.
alias \
	ls="ls -h --color=auto" \
	grep="grep --color=auto" \
	fgrep="fgrep --color=auto" \
	egrep="egrep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# ls shortcuts
alias \
	ll="ls -alF" \
	la="ls -A" \
	l="ls -CF"

alias \
	tmux="tmux -f \$XDG_CONFIG_HOME/tmux/tmux.conf" \

alias mapscii="telnet mapscii.me"
