#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -v" \
	mv="mv -v" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	vim="nvim" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

alias \
	tmux="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf" \
	yay="yay --config ${XDG_CONFIG_HOME}/pacman/pacman.conf"

alias cls="ls -la | awk   '{k=0;for(i=0;i<=8;i++)k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(\"%0o \",k);print}'"

alias drag="dragon-drop"
alias mapscii="telnet mapscii.me"
alias connect="networkmanager_dmenu"
alias timezone="timedatectl set-timezone \"\$(curl --fail https://ipapi.co/timezone)\""
